Use spotless for CI lint
google/jetpack-camera-app pull request #57
Opened 2023-10-11 19:57 UTC by yasith

2023-10-11 19:57 UTC, yasith commented
Current dependencies on/for this PR:
* main
  * **PR #52** <a href="https://app.graphite.dev/github/pr/google/jetpack-camera-app/52" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #51** <a href="https://app.graphite.dev/github/pr/google/jetpack-camera-app/51" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #53** <a href="https://app.graphite.dev/github/pr/google/jetpack-camera-app/53" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
        * **PR #54** <a href="https://app.graphite.dev/github/pr/google/jetpack-camera-app/54" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
          * **PR #56** <a href="https://app.graphite.dev/github/pr/google/jetpack-camera-app/56" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
            * **PR #57** <a href="https://app.graphite.dev/github/pr/google/jetpack-camera-app/57" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/google/jetpack-camera-app/57?utm_source=stack-comment).

2023-10-12 04:41 UTC, yasith commented on .github/workflows/BuildAndTest.yaml
> -on: [push, pull_request]
This was causing the jobs to run twice per each PR update, so I changed it to just push

2023-10-12 04:43 UTC, yasith commented on .github/workflows/BuildAndTest.yaml
> -        run: ./gradlew test
Split this into a separate job, so it runs in parallel.

Also makes it clearer in the interface about what checks are passing/failing/in-progress.

<img width="917" alt="Screenshot 2023-10-12 at 12 33 55 AM" src="https://github.com/google/jetpack-camera-app/assets/417355/c239ddbe-5b4f-4090-ae93-7275b81c6737">

2023-10-12 19:36 UTC, temcguir requested changes

2023-10-12 19:36 UTC, temcguir commented on .github/workflows/PushWorkflow.yaml
> +      - name: Upload build reports
With this change, the "Unit Tests" task will no longer uploads test reports (stored in `build/reports/tests`) that are generated on failure. We should add an "Upload unit test reports" using `if: failure()` in the `tests` job.

2023-10-12 19:36 UTC, temcguir commented on .github/workflows/PushWorkflow.yaml
> +          path: app/build/reports
I think I missed this in the original workflow, but we should include the build reports for all of the modules. I think you can replace `app/build/reports` with `**/build/reports`.

2023-10-13 06:40 UTC, temcguir approved these changes

2023-10-13 14:57 UTC, merged