Loading screen permissions
google/jetpack-camera-app pull request #61
Opened 2023-10-12 17:34 UTC by Kimblebee

Updated UI for Camera Permission Request
Created a reusable template that can be used when requesting other permissions in the future, i.e. microphone

2023-10-13 00:52 UTC, yasith requested changes

2023-10-13 00:52 UTC, yasith commented on app/src/main/res/values/strings.xml
> +    <string name="image_accessibility_text">A symbol representing a camera</string>
nit: the name should be specific to the camera icon image.

eg. `camera_permission_image_accessibility_text`

2023-10-13 00:52 UTC, yasith commented on app/src/main/java/com/google/jetpackcamera/ui/PermissionsUi.kt
> +                        //todo: skip permission button for optional permissions
//TODO(name/bug): details..

2023-10-13 00:52 UTC, yasith commented on app/src/main/java/com/google/jetpackcamera/ui/PermissionsUi.kt
> +        // permission image / top half
I think the comments you have are perfect places to extract out into sub Composables.

2023-10-13 01:56 UTC, yasith reviewed
Can you add screenshots of the change to the PR, makes it easier to review visual changes.

2023-10-16 20:03 UTC, Kimblebee commented
![image](https://github.com/google/jetpack-camera-app/assets/20013168/133d0e6e-660a-439a-a40a-b3cd283ff1f0)

![image](https://github.com/google/jetpack-camera-app/assets/20013168/d630d8c3-1525-4eab-bdec-1110fe18f8e6)
screens with/without skip button text

2023-10-16 20:28 UTC, yasith commented
> ![image](https://user-images.githubusercontent.com/20013168/275636401-133d0e6e-660a-439a-a40a-b3cd283ff1f0.png)
> 
> ![image](https://user-images.githubusercontent.com/20013168/275635195-d630d8c3-1525-4eab-bdec-1110fe18f8e6.png) screens with/without skip button text

This looks very nice!!

2023-10-16 22:44 UTC, Kimblebee commented on app/src/main/java/com/google/jetpackcamera/ui/PermissionsUi.kt
> +                        //modifier = Modifier.align(Alignment.Start),
yeah just leftovers when i was working through the layout. removed

2023-10-16 22:56 UTC, Kimblebee commented on app/src/main/java/com/google/jetpackcamera/ui/PermissionsUi.kt
> +                        //todo: skip permission button for optional permissions
actually no longer necessary

2023-10-17 16:19 UTC, yasith approved these changes

2023-10-17 16:19 UTC, yasith commented on app/src/main/java/com/google/jetpackcamera/ui/PermissionsUi.kt
> +
nit: extra new line

2023-10-17 22:10 UTC, merged