Fix reset of front facing camera settings after leaving screen settings
google/jetpack-camera-app pull request #75
Opened 2023-10-27 09:34 UTC by mrxx0

updateAvailableCameraLens function always set the settings of front facing camera to true if the front facing camera is available, by removing the call to setDefaultFrontCamera the front camera is not set to true as a default value and fix the issue.

2023-11-07 19:40 UTC, yasith commented
Hi @mrxx0 thank you for the pull request. Sorry about the delay getting back to you. We'll take a look soon

2023-11-09 10:19 UTC, mrxx0 commented
> Hi @mrxx0 thank you for the pull request. Sorry about the delay getting back to you. We'll take a look soon

Thank you, just rebased your main branch on mine

2023-11-13 18:02 UTC, Kimblebee requested changes

2023-11-13 19:23 UTC, mrxx0 commented on data/settings/src/main/java/com/google/jetpackcamera/settings/LocalSettingsRepository.kt
> -                .setDefaultFrontCamera(frontLensAvailable)
Thank you for the feedback @Kimblebee your addition is indeed needed  for the case of the one camera device.
PR updated.

2023-11-14 18:06 UTC, Kimblebee approved these changes

2023-11-27 18:15 UTC, Kimblebee commented
hi there, it seems like the checks did not finish running for some reason, and the branch is now out of sync with main. could you update the branch to re-trigger the checks, and since it has been approved it should be good to merge!

2023-11-27 18:59 UTC, Kimblebee commented
spotless check failed, you'll just need to run `./gradlew spotlessApply --init-script gradle/init.gradle.kts --stacktrace`

2023-11-27 21:47 UTC, Kimblebee commented
should be good to merge now :-)

2023-11-28 02:13 UTC, merged